# --- DFTD2/DFTD3 possible damping & xc combinations ---

# damping, xc, old
damping_xc_combination_list = [
    ("bjm", "b2-plyp", False),
    ("bjm", "b3-lyp", False),
    ("bjm", "b97-d", False),
    ("bjm", "b-lyp", False),
    ("bjm", "b-p", False),
    ("bjm", "pbe", False),
    ("bjm", "pbe0", False),
    ("bjm", "lc-wpbe", False),
    ("zerom", "b2-plyp", False),
    ("zerom", "b3-lyp", False),
    ("zerom", "b97-d", False),
    ("zerom", "b-lyp", False),
    ("zerom", "b-p", False),
    ("zerom", "pbe", False),
    ("zerom", "pbe0", False),
    ("zerom", "lc-wpbe", False),
    ("bj", "b-p", False),
    ("bj", "b-lyp", False),
    ("bj", "revpbe", False),
    ("bj", "rpbe", False),
    ("bj", "b97-d", False),
    ("bj", "pbe", False),
    ("bj", "rpw86-pbe", False),
    ("bj", "b3-lyp", False),
    ("bj", "tpss", False),
    ("bj", "hf", False),
    ("bj", "tpss0", False),
    ("bj", "pbe0", False),
    ("bj", "hse06", False),
    ("bj", "revpbe38", False),
    ("bj", "pw6b95", False),
    ("bj", "b2-plyp", False),
    ("bj", "dsd-blyp", False),
    ("bj", "dsd-blyp-fc", False),
    ("bj", "bop", False),
    ("bj", "mpwlyp", False),
    ("bj", "o-lyp", False),
    ("bj", "pbesol", False),
    ("bj", "bpbe", False),
    ("bj", "opbe", False),
    ("bj", "ssb", False),
    ("bj", "revssb", False),
    ("bj", "otpss", False),
    ("bj", "b3pw91", False),
    ("bj", "bh-lyp", False),
    ("bj", "revpbe0", False),
    ("bj", "tpssh", False),
    ("bj", "mpw1b95", False),
    ("bj", "pwb6k", False),
    ("bj", "b1b95", False),
    ("bj", "bmk", False),
    ("bj", "cam-b3lyp", False),
    ("bj", "lc-wpbe", False),
    ("bj", "b2gp-plyp", False),
    ("bj", "ptpss", False),
    ("bj", "pwpb95", False),
    ("bj", "hf/mixed", False),
    ("bj", "hf/sv", False),
    ("bj", "hf/minis", False),
    ("bj", "b3-lyp/6-31gd", False),
    ("bj", "hcth120", False),
    ("bj", "dftb3", False),
    ("bj", "pw1pw", False),
    ("bj", "pwgga", False),
    ("bj", "hsesol", False),
    ("bj", "hf3c", False),
    ("bj", "hf3cv", False),
    ("bj", "pbeh3c", False),
    ("bj", "pbeh-3c", False),
    ("zero", "slater-dirac-exchange", False),
    ("zero", "b-lyp", False),
    ("zero", "b-p", False),
    ("zero", "b97-d", False),
    ("zero", "revpbe", False),
    ("zero", "pbe", False),
    ("zero", "pbesol", False),
    ("zero", "rpw86-pbe", False),
    ("zero", "rpbe", False),
    ("zero", "tpss", False),
    ("zero", "b3-lyp", False),
    ("zero", "pbe0", False),
    ("zero", "hse06", False),
    ("zero", "revpbe38", False),
    ("zero", "pw6b95", False),
    ("zero", "tpss0", False),
    ("zero", "b2-plyp", False),
    ("zero", "pwpb95", False),
    ("zero", "b2gp-plyp", False),
    ("zero", "ptpss", False),
    ("zero", "hf", False),
    ("zero", "mpwlyp", False),
    ("zero", "bpbe", False),
    ("zero", "bh-lyp", False),
    ("zero", "tpssh", False),
    ("zero", "pwb6k", False),
    ("zero", "b1b95", False),
    ("zero", "bop", False),
    ("zero", "o-lyp", False),
    ("zero", "o-pbe", False),
    ("zero", "ssb", False),
    ("zero", "revssb", False),
    ("zero", "otpss", False),
    ("zero", "b3pw91", False),
    ("zero", "revpbe0", False),
    ("zero", "pbe38", False),
    ("zero", "mpw1b95", False),
    ("zero", "mpwb1k", False),
    ("zero", "bmk", False),
    ("zero", "cam-b3lyp", False),
    ("zero", "lc-wpbe", False),
    ("zero", "m05", False),
    ("zero", "m052x", False),
    ("zero", "m06l", False),
    ("zero", "m06", False),
    ("zero", "m062x", False),
    ("zero", "m06hf", False),
    ("zero", "hcth120", False),
    # skip tz=True of damping="zero".
    # "b-lyp"
    # "b-p"
    # "b97-d"
    # "revpbe"
    # "pbe"
    # "tpss"
    # "b3-lyp"
    # "pbe0"
    # "pw6b95"
    # "tpss0"
    # "b2-plyp"
    ("zero", "b-lyp", True),
    ("zero", "b-p", True),
    ("zero", "b97-d", True),
    ("zero", "revpbe", True),
    ("zero", "pbe", True),
    ("zero", "tpss", True),
    ("zero", "b3-lyp", True),
    ("zero", "pbe0", True),
    ("zero", "pw6b95", True),
    ("zero", "tpss0", True),
    ("zero", "b2-plyp", True),
    ("zero", "b2gp-plyp", True),
    ("zero", "dsd-blyp", True),
]

# damping, old
damping_method_list = [
    ("zero", False),
    ("bj", False),
    ("zerom", False),
    ("bjm", False),
    ("zero", True),
]
