configs {
  # Project name.
  key: "torch-dftd.pytest"
  value {
    requirement {
      cpu: 6
      memory: 36
      disk: 10
      gpu: 1
    }
    time_limit {
      seconds: 1800
    }
    command:
        "bash -x .flexci/pytest_script.sh"
  }
}
