configs {
  # Project name.
  key: "torch-dftd.pytest"
  value {
    requirement {
      cpu: 4
      memory: 24
      disk: 10
      gpu: 1
    }
    command:
        "bash -x .flexci/pytest_script.sh"
  }
}
