"""Generate torch_dftd/nn/params/dftd4_params.npz and dftd4_xc_params.py.

Reference data are taken from the ``tad-dftd4`` / ``tad-mctc`` / ``tad-multicharge`` Python
packages (Apache-2.0), which in turn tabulate the DFT-D4 reference systems of the ``dftd4``
Fortran library (LGPL-3.0, Caldeweyher et al., J. Chem. Phys. 150, 154122 (2019)).
The damping parameters are read from ``dftd4``'s ``parameters.toml`` (``d4.bj-eeq-atm`` set).
Run once (needs tad-dftd4 and dftd4 installed):  python tools/gen_dftd4_params.py
"""
import os, sys, json
import numpy as np, torch

here = os.path.dirname(os.path.abspath(__file__))
out_dir = os.path.join(here, "..", "torch_dftd", "nn", "params")

from tad_dftd4.reference import d4 as ref
from tad_dftd4.reference.d4.charge_eeq import clsq, clsh
from tad_dftd4 import data
from tad_mctc.data import radii, en
from tad_multicharge.param import eeq2019

GA, GC = 3.0, 2.0
nz = 104  # index by atomic number, 0 = dummy


def zeta(gam, qref, qmod):
    scale = torch.exp(gam * (1.0 - qref / qmod))
    return torch.where(qmod > 0.0, torch.exp(GA * (1.0 - scale)), torch.exp(torch.tensor(GA, dtype=gam.dtype)))


with torch.no_grad():
    dd = dict(dtype=torch.float64)
    refsys = ref.refsys[:nz]                       # (nz, 7) int
    refascale = ref.refascale[:nz].to(**dd)
    refalpha = ref.refalpha[:nz].to(**dd)          # (nz, 7, 23)
    refscount = ref.refscount[:nz].to(**dd)
    secscale = ref.secscale.to(**dd)               # (18, 1)
    secalpha = ref.secalpha.to(**dd)               # (18, 23)
    refsq = clsh[:nz].to(**dd)
    mask = refsys > 0
    zeff_s = data.ZEFF("cpu")[refsys].to(**dd)
    gam_s = data.GAM(**dd)[refsys] * GC
    z = torch.where(mask, zeta(gam_s, zeff_s, refsq + zeff_s), torch.tensor(0.0, **dd))
    aiw = secscale[refsys] * secalpha[refsys] * z.unsqueeze(-1)   # (nz,7,23)
    alpha = refascale.unsqueeze(-1) * (refalpha - refscount.unsqueeze(-1) * aiw)
    alpha = torch.where(alpha > 0.0, alpha, torch.tensor(0.0, **dd))  # (nz, 7, 23) reference polarizabilities
    w = torch.tensor([2.49995e-2, 4.99995e-2, 7.500000000000001e-2, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.15, 0.2, 0.2, 0.2, 0.2,
                      0.35, 0.5, 0.75, 1.0, 1.75, 2.5, 1.25], **dd)
    rc6 = (3.0 / np.pi) * torch.einsum("w,iaw,jbw->ijab", w, alpha, alpha)  # (nz, nz, 7, 7)

    np.savez_compressed(
        os.path.join(out_dir, "dftd4_params.npz"),
        rc6=rc6.numpy().astype(np.float64),
        refc=ref.refc[:nz].numpy().astype(np.int64),
        refcovcn=ref.refcovcn[:nz].numpy().astype(np.float64),
        refq=clsq[:nz].numpy().astype(np.float64),
        rcov=radii.COV_D3(**dd)[:nz].numpy(),
        r4r2=data.R4R2(**dd)[:nz].numpy(),
        en=en.PAULING(**dd)[:nz].numpy(),
        zeff=data.ZEFF("cpu")[:nz].numpy().astype(np.float64),
        gam=data.GAM(**dd)[:nz].numpy(),
        eeq_chi=eeq2019.chi[:nz].numpy().astype(np.float64),
        eeq_eta=eeq2019.eta[:nz].numpy().astype(np.float64),
        eeq_kcn=eeq2019.kcn[:nz].numpy().astype(np.float64),
        eeq_rad=eeq2019.rad[:nz].numpy().astype(np.float64),
    )
    print("wrote dftd4_params.npz  rc6", tuple(rc6.shape))

# damping parameters from dftd4's parameters.toml
try:
    import tomllib
except ImportError:
    import tomli as tomllib
import dftd4
toml = os.path.join(os.path.dirname(dftd4.__file__), "parameters.toml")
with open(toml, "rb") as fh:
    par = tomllib.load(fh)
table = {}
for name, entry in par["parameter"].items():
    p = entry.get("d4", {}).get("bj-eeq-atm")
    if p is None:
        continue
    table[name.lower()] = {"s6": float(p.get("s6", 1.0)), "s8": float(p["s8"]), "s9": float(p.get("s9", 1.0)),
                           "a1": float(p["a1"]), "a2": float(p["a2"]), "alp": float(p.get("alp", 16.0))}
with open(os.path.join(here, "..", "torch_dftd", "dftd4_xc_params.py"), "w") as fh:
    fh.write('"""DFT-D4 (BJ damping, EEQ charges, ATM) damping parameters, generated by tools/gen_dftd4_params.py\n'
             'from dftd4 parameters.toml (d4.bj-eeq-atm set). Do not edit by hand."""\n')
    fh.write("from typing import Dict\n\n_DFTD4_PARAMS: Dict[str, Dict[str, float]] = " + json.dumps(table, indent=1) + "\n\n")
    fh.write('''

def get_dftd4_default_params(xc: str = "pbe") -> Dict[str, float]:
    """Return DFT-D4 damping parameters {s6, s8, s9, a1, a2, alp} for the functional ``xc``.

    Names are case-insensitive; hyphens are ignored (``"r2scan"``, ``"pbe0"``, ``"b3-lyp"`` ...).
    """
    key = xc.lower().replace("-", "")
    for k, v in _DFTD4_PARAMS.items():
        if k.replace("-", "") == key:
            return dict(v)
    raise ValueError(f"Unknown xc functional for DFT-D4: {xc!r}. Available: {sorted(_DFTD4_PARAMS)}")
''')
print("wrote dftd4_xc_params.py with", len(table), "functionals; pbe =", table["pbe"])
